### PR TITLE
add docs for tree_utils module

### LINKED ISSUE #685: Add the tree_util module to the API documentation

### PR DESCRIPTION
**Pull request by amosyou**
Added documentation for tree utilities which fixes #685

### CODE REVIEW

**Comment by fabianp** [comment]
this is great, thank you so much @amosyou ! 

Small request: instead of putting these in a new file docs/api/tree_utilities.rst, would you mind putting them in the file docs/api/general_utilities.rst and then rename that file to docs/api/utilities.rst ?

We're trying to reduce the number of items under API documentation.

**Comment by amosyou** [comment]
sure thing @fabianp ! and then would it be cool if I also put the utilities for numerical stability and second order optimization in the utilities.rst?

**Comment by fabianp** [comment]
+100 that would be just perfect

**Comment by amosyou** [comment]
@fabianp combined everything into one utilities.rst, let me know if there's any other changes you'd see fit

**Review by fabianp — APPROVED** [review]
Perfection, thanks!!!

**Comment by vroulet** [comment]
Thank you @amosyou ! A tiny little detail: could you order the Tree functions alphabetically? The rest of the doc is ordered that way, even though your order made sense too. Thanks again!

**Comment by amosyou** [comment]
sounds good @vroulet ! should we also reorder the types of util functions to be alphabetical (ie. general, numerical stability, second order, tree) or is the current ordering fine?

**Comment by vroulet** [comment]
Yes, let's be systematic. Thanks again!

**Comment by fabianp** [comment]
merged, thanks @amosyou !

**Pull request merged**
