### PR TITLE
As/add focal loss

### PR DESCRIPTION
**Pull request by paganpasta**
Adding focal loss as per discussion: https://github.com/deepmind/optax/issues/525

- [x] Implementation of the loss
- [x] Documentation string
- [x] Test code
- [ ] execute bash test.sh

Currently, One test fails 
```
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
/tmp/optax-env/lib/python3.10/site-packages/optax/_src/equivalence_test.py:21: in <module>
    from flax import optim
/tmp/optax-env/lib/python3.10/site-packages/flax/__init__.py:19: in <module>
    from . import linen as linen
/tmp/optax-env/lib/python3.10/site-packages/flax/linen/__init__.py:47: in <module>
    from .attention import (
/tmp/optax-env/lib/python3.10/site-packages/flax/linen/attention.py:22: in <module>
    from flax.linen.linear import default_kernel_init
/tmp/optax-env/lib/python3.10/site-packages/flax/linen/linear.py:30: in <module>
    from jax import ShapedArray
E   ImportError: cannot import name 'ShapedArray' from 'jax' (/tmp/optax-env/lib/python3.10/site-packages/jax/__init__.py)

```

@mtthss Any suggestion on how to fix this error?

### CODE REVIEW

**Comment by v0lta** [comment]
I want to suggest a change to the alpha parameter. Please give me a minute to create a PR.

**Comment by mtthss** [comment]
Can you sync so we get this CL merged?

**Comment by fabianp** [comment]
PR #599 proposes to implement the same loss (if I understood it correctly)

**Comment by paganpasta** [comment]
> PR #599 proposes to implement the same loss (if I understood it correctly)

Hi, thanks for the response. 

Yes, the other PR proposes a similar functionality but focuses on a single class case (sigmoid). 

I think, a unified approach which handles both multi class and single class would be ideal. Or, having two different functions clearly identifying the differences could also work. 

Looking forward to hearing your thoughts.

**Comment by fabianp** [comment]
Thanks @paganpasta . Given the other function has 'sigmoid' in the name (which is consistent with the original implementation https://github.com/facebookresearch/fvcore/blob/main/fvcore/nn/focal_loss.py), I think implementing a non-sigmoid one would make more sense API-wise as a different function

**Comment by fabianp** [comment]
Closing this issue PR, please reopen or open a new one if you contribute the general focal loss

**Pull request closed without merging**
