### PR TITLE
Remove unnecessary %pip install statements from the notebooks

### PR DESCRIPTION
**Pull request by JayJayleee**
This PR removes unnecessary %pip install statements from [adversarial_training.ipynb](https://github.com/google-deepmind/optax/blob/main/examples/adversarial_training.ipynb) and [cifar10_resnet.ipynb](https://github.com/google-deepmind/optax/blob/main/examples/cifar10_resnet.ipynb)  from examples.

Addressing issue https://github.com/google-deepmind/optax/issues/756

### CODE REVIEW

**Comment by fabianp** [comment]
Thanks @JayJayleee ! Could you make sure that nothing outside the of the %pip install statements is changed? In particular, I see from the diff that the metadata has changed and some outputs have been supressed

**Comment by JayJayleee** [comment]
> Thanks @JayJayleee ! Could you make sure that nothing outside the of the %pip install statements is changed? In particular, I see from the diff that the metadata has changed and some outputs have been supressed

I'm sorry, it seems there was a mistake in reviewing the code.
I rechecked and PR  in https://github.com/google-deepmind/optax/pull/761

**Comment by fabianp** [comment]
Thanks a lot @JayJayleee ! 

The execution_count in the adversarial training example is on purpose set differently. It's set to -1 to [avoid timeout](https://myst-nb.readthedocs.io/en/v0.9.0/use/execute.html#execution-timeout) , so its important that we leave it like that :-)

**Comment by fabianp** [comment]
> > Thanks @JayJayleee ! Could you make sure that nothing outside the of the %pip install statements is changed? In particular, I see from the diff that the metadata has changed and some outputs have been supressed
> 
> I'm sorry, it seems there was a mistake in reviewing the code. I rechecked and updated the PR in #762
> 
> Also, I noticed that in adversarial_training.ipynb, the execution_count is a number, while in other files it's set to null. I followed the respective format for each file, but should I unify them?

Excellent, that other PR looks good to me. It's now in the merge queue (might take a couple of days top, probably just a few hours)

**Pull request closed without merging**
