### PR TITLE
Add ACProp optimizer.

### PR DESCRIPTION
**Pull request by carlosgmartin**
#965

### CODE REVIEW

**Comment by carlosgmartin** [comment]
@fabianp @vroulet This PR is getting the same error as https://github.com/google-deepmind/optax/pull/962. Looks like there's a problem with `optax/monte_carlo/control_variates_test.py` `ConsistencyWithStandardEstimators.testWeightedLinearFunction`?

**Comment by vroulet** [comment]
Yep, we know. This bug does not show up internally, neither on a mac, just on linux (which I don't have).
It's related to the new jax release. We are working on it.

**Comment by vroulet** [comment]
It's been fixed in #972. Should be merged tomorrow.

**Review by vroulet — COMMENTED** [review]
Thanks one more time for this contribution @carlosgmartin 
This looks very good.
One additional comment: since this paper is cited only 6 times, we will place it in the contrib folder for now, see https://optax.readthedocs.io/en/latest/development.html#inclusion-criteria
(that's a policy implemented only recently)

**Comment by carlosgmartin** [comment]
@vroulet Done.

**Comment by vroulet** [comment]
Thanks! Can you add it to the list of common tests of the contrib folder?

**Comment by carlosgmartin** [comment]
@vroulet Done.

**Review by vroulet — APPROVED** [review]
Perfect, thank you again @carlosgmartin.
- The scale_by_sophia can be added to the doc.
- You may format the reference in scale_by_sophia.
- The copyright should be 2024.
I can take it from here if you don't have time.
We sincerely appreciate the dedication in your PRs.

**Comment by carlosgmartin** [comment]
@vroulet Did you mean adding `scale_by_acprop` to `docs/api/contrib.rst` in your first bullet point?

**Comment by vroulet** [comment]
Yes. People may want to combine this scale function with e.g. a clipping.

**Comment by vroulet** [comment]
Perfect, I'll take it from here (I need to make some internal changes to add this optimizer to our builds). 
Thanks again

**Comment by carlosgmartin** [comment]
@vroulet Should I close this now?

**Comment by vroulet** [comment]
It should have been closed automatically but yes, let me close it

**Pull request closed without merging**
