### PR TITLE
Fixed Issue #229

### PR DESCRIPTION
**Pull request by Warlord-K**
Addeed Examples from Readme to Optax-101.ipynb to Fix Issue #229

### CODE REVIEW

**Comment by rosshemsley** [comment]
Hey @Warlord-K - I am working on getting this rendered so I can take a look at it.

In the mean time, do you think you could format the JSON so that it matches the original format? This will ensure the diff is clean and will help me see what has changed.

**Comment by Warlord-K** [comment]
> Hey @Warlord-K - I am working on getting this rendered so I can take a look at it.
> 
> In the mean time, do you think you could format the JSON so that it matches the original format? This will ensure the diff is clean and will help me see what has changed.

Okay I will try to fix it

**Comment by amosyou** [comment]
hey @Warlord-K @rosshemsley, happy to hop in and help with this one if this is still relevant

**Comment by fabianp** [comment]
@amosyou : yes please  , it would be great if you can take over so we can get it merged 🙌🏼

**Comment by amosyou** [comment]
@fabianp sorry this is my first time contributing to open source, should I make these changes and push to @Warlord-K 's fork or should I do it in mine?

**Comment by fabianp** [comment]
Better to create a new branch in your repo and push there. You usually don't have permissions to push to other people's forks

**Comment by amosyou** [comment]
I created a new PR #726, wasn't sure how to add my commits from my fork to this existing PR

**Comment by fabianp** [comment]
closing in favor of https://github.com/google-deepmind/optax/pull/726

**Pull request closed without merging**
