### PR TITLE
chore(build): migrate to pyproject

### PR DESCRIPTION
**Pull request by SauravMaheshkar**
This PR aims to build on top of the work done in #513, and complete the migration to a pure `pyproject.toml` based build.

Changes made by this PR can be summarised as follows:

* delete `setup.py` and `MANIFEST.in`
* update `pyproject.toml` to include the `LICENSE` and `README` in the package.

Request for Review: @fabianp

### CODE REVIEW

**Comment by fabianp** [comment]
yup. It seems to be due to the recent release of pytest 8.0.0. Downgrading seems to solve the issue (https://github.com/google-deepmind/optax/pull/743) although its not ideal as a long-term solution

**Comment by fabianp** [comment]
Update: I think a better solution is https://github.com/google-deepmind/optax/pull/746
comments welcome

**Comment by SauravMaheshkar** [comment]
> Update: I think a better solution is #746 comments welcome

Much nicer compared to downgrading ❤️

**Review by fabianp — APPROVED** [review]

**Comment by SauravMaheshkar** [comment]
@fabianp Anything else I can do on my end to help out ?

**Comment by fabianp** [comment]
Implemented through https://github.com/google-deepmind/optax/commit/f0dfdaa8fa3d673aa56882da2edc26f93834bdf3 . Sorry for the code duplication, at the end I had to do this from the google side to fix some internal errors

**Pull request closed without merging**
