### PR TITLE
fix the default learning rate in prodigy

### PR DESCRIPTION
**Pull request by konstmish**
fixing the current version of Prodigy that has a typo: the learning was set to 0.1 instead of 1.0

### CODE REVIEW

**Comment by fabianp** [comment]
Thanks Konstantin! The changes look good to me. 

The tests are failing, seems to me for unrelated reasons .... i'm looking into it

**Review by fabianp — APPROVED** [review]
Thanks Konstantin!

**Comment by vroulet** [comment]
Thanks @konstmish! The prodigy test fails with this default learning rate. To fix this, it suffices to change the test for the algorithm to run for 100 000 iterations instead of 10 000 iterations. Could you take care of it in this PR? Thanks!

**Comment by fabianp** [comment]
There seems to be anyway something wrong with the CI. Everything is failing with an obscure `==== ERROR ../::tmp - PermissionError: [Errno 13] Permission denied: '/tmp/snap-private-tmp/__init__.py'`

**Comment by fabianp** [comment]
seems its a problem with the most recent release of pytest. Downgrading it seemed to solve the issue: https://github.com/google-deepmind/optax/pull/743

**Comment by fabianp** [comment]
should be fixed now in main (https://github.com/google-deepmind/optax/commit/2e69e7f5b23ba50d613e0a1846cacbb62707aafa). Please update this branch and 🤞🏼

**Pull request merged**
