### PR TITLE
Add the Nadam optimizer

### PR DESCRIPTION
**Pull request by Rupt**
Nadam is Adam with Nesterov's correction. It is recommended by the [Deep Learning Tuning Playbook](https://github.com/google-research/tuning_playbook#choosing-the-optimizer).

This PR adapts @AntoinePlumerault's excellent work in https://github.com/deepmind/optax/pull/529 to
- Pass the tests, by tree mapping, safe incrementing, and reducing `learning_rate` in `alias_test`.
- Not include an extra `b2` scale factor on the second moment estimate.
  This multiplier only appears in the [2016 OpenReview paper](https://openreview.net/forum?id=OM0jvwB8jIp57ZJjtNEZ), and I believe it might be a typographic error because I see no explanation. [Other](https://github.com/keras-team/keras/blob/b3ffea6602dbbb481e82312baa24fe657de83e11/keras/optimizers/nadam.py#L174) [versions](https://pytorch.org/docs/stable/generated/torch.optim.NAdam.html) [also](https://arxiv.org/abs/1910.05446) [exclude](https://cs229.stanford.edu/proj2015/054_report.pdf) it.
- Document the mathematical form we implement.
  The versions linked above differ by their "bias correction" factors go. This implementation matches [Torch](https://pytorch.org/docs/stable/generated/torch.optim.NAdam.html) and [Keras](https://github.com/keras-team/keras/blob/b3ffea6602dbbb481e82312baa24fe657de83e11/keras/optimizers/nadam.py#L171) (for constant `b1`).

In this PR, we:
- Add the Nadam transform and optimizer alias.
- Make minor tidy-ups: remove some inconsistent whitespace, place `scale_by_lion` alphabetically.

Merges #570 so that tests pass.

Ticks one off #507

### CODE REVIEW

**Comment by fabianp** [comment]
hey @Rupt , any reason why this PR got closed? perhaps by mistake?

**Comment by Rupt** [comment]
Hi @fabianp, I was just cleaning up after I got the impression that this project was inactive on the public (outside-google) site.
I am more than happy to re-open this if there is interest.

**Comment by fabianp** [comment]
Excellent! A bunch of us are working hard on reviving the project and creating a vibrant community around it (not just for Googlers!) 🤗 . We're working on solving a big backlog of issues, and this one is very high on our priority list 

if you reopen the issue I think we can get it merged real quickly 🚀

**Comment by Rupt** [comment]
That's great news! Thank you for saying. I'll try to have a got at that this evening.

**Comment by fabianp** [comment]
Excellent. Just to be clear, I just need to you to reopne this PR (I can't do that myself). Then I can take care of the last polishing before merging

**Comment by fabianp** [comment]
reopening

**Comment by fabianp** [comment]
OK I think I understand now better why I can't reopen the PR. The branch Rupt:nadam seems to be deleted. Hope you can get back the code easily @Rupt (but of course no rush)!

**Comment by Rupt** [comment]
Redone in #719. Indeed, I made the mistake of deleting this branch, but I am glad that you've raised it again. :)

**Pull request closed without merging**
