### PR TITLE
Moved linear algebra operations into utilities

### PR DESCRIPTION
**Pull request by hmludwig**
See #831

### CODE REVIEW

**Review by fabianp — APPROVED** [review]

**Comment by fabianp** [comment]
looks great to me, thanks @hmludwig !

**Comment by vroulet** [comment]
I would either
- remove multi_normal to the docs
- add a docstring to multi_normal

Currently the doc of multi_normal is uninformative.

**Comment by fabianp** [comment]
huh, I hadn't realized about this function. I wonder why we need the function multi_normal in the first place

**Comment by vroulet** [comment]
I let it merged and opened a different issue concerning multi_normal.
Thank you @hmludwig for this PR!

**Pull request merged**
