### PR TITLE
Extend example gallery entry for linear assignment problem with optimal transport example.

### PR DESCRIPTION
**Pull request by carlosgmartin**
Follow-up to https://github.com/google-deepmind/optax/pull/1083#issuecomment-2407808657.

See also https://github.com/ott-jax/ott/pull/598.

### CODE REVIEW

**Review by vroulet — APPROVED** [review]
Thanks @carlosgmartin, looks good to me. I'll approve this too.
I don't understand what this other link on ott is about. By curiosity can you explain to me the link?

**Comment by carlosgmartin** [comment]
@vroulet Just noting that ott-jax is now using optax's Hungarian algorithm for unregularized OT solving.

**Comment by vroulet** [comment]
Very nice!

**Comment by fabianp** [comment]
Thanks Carlos, this is super nice! ❤️

**Pull request merged**
