### PR TITLE
Added reduce_on_plateau

### PR DESCRIPTION
**Pull request by OhadRubin**

### CODE REVIEW

**Comment by OhadRubin** [comment]
@mkunesch @LukasMut @rosshemsley

**Comment by vz415** [comment]
HI @OhadRubin, I'd like to use this scheduler and was wondering if you planned on signing the CLA? If not, I'd be interested in merging this if you don't mind.

**Comment by OhadRubin** [comment]
I signed the CLA in February 26th.

**Comment by mtthss** [comment]
Apologies for the very slow turnaround on this, I was on paternity leave.

Can you move this under optax/contrib/ and use the new GradientTransformationWithExtraArgs API that was merged in the main branch instead of the old one in experimental/?

**Comment by fabianp** [comment]
Going to close this one since we just merged #629 , which implements the same schedule . If you feel like some functionality is missing, please don't hesitate to open another pull request against this implementation

**Pull request closed without merging**
